[tool.poetry]
name = "magstats-step"
version = "0.1.0"
description = ""
authors = ["ASHuenchuleo <arsepulh@gmail.com>"]
readme = "README.md"
packages = [{include = "magstats_step"}]

[tool.poetry.dependencies]
python = "~3.9.0"
apf-base = "^1.0.9"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
