name: unit_test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'magstats_step/**'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
      working-directory: ./
    - name: Test with pytest
      run: |
         poetry run pytest tests/unittest/
      working-directory: ./
